app = 'puro-suco-newsletter'
primary_region = 'gru'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[env]
  NODE_ENV = 'production'

# VM configuration for better performance
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Keep machines running (important for newsletter watcher)
[experimental]
  auto_rollback = true

[[mounts]]
  source = 'data'
  destination = '/app/data'